### ISSUE TITLE
Change run() to convert() or markdown() to be consistent with original Markdown package

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/kordac#34]
Worth investigating if this suggestion is sensible.

**Comment by hayleyavw** [comment]
I'll look into this since I am doing a bit of refactoring at the moment.

**Comment by ravenmaster001** [comment]
@JackMorganNZ 
I think we should rename this method to `convert` as that is what the method does. To me `run` would imply that I am starting kordac up (as a service or otherwise) to feed in multiple documents. I don't believe we should call it `markdown` as I feel this is ambiguous and does not describe well that kordac is actually being used.

**Comment by JackMorganNZ** [comment]
I can see both sides. But I would like to point out that I picked those names from the original Markdown package.

`markdown` is the name for the one off conversion.

`convert` is the name of the method used on the converter ([docs here](http://pythonhosted.org/Markdown/reference.html#Markdown)).

My preferred name would be `convert` for the reasons you suggested above (describes purpose better), plus consistency with the original package.

Thoughts?

**Comment by ravenmaster001** [comment]
I think if we are both agreeing on `convert` without argument that is really what should be chosen.
