### ISSUE TITLE
Investigate if tests should be included in package/module

### ISSUE THREAD

**Issue by ravenmaster001** [uccser/kordac#52]
Currently are available if you download the repository, but not available if you install the package from PIP (once it's uploaded).

@hayleyavw can you elaborate why the tests are not in the package

**Comment by hayleyavw** [comment]
The tests sit at the same level as the `kordac/` directory, I suspect this has something to do with it, but this is just a best guess.

**Comment by JackMorganNZ** [comment]
@hayleyavw I think Hayden is asking if this is the desired behaviour (this is how our repo currently works):

- Once we upload Kordac to PIP, if you go `pip install kordac` it **won't** have the tests, because they are outside the package folder.
- If you download the development version of Kordac from GitHub, it **will** have the tests as they are cloning the whole repository.

Flicking through websites, it seems like the most common practice to include tests in the package. However there are projects which are doing it the way we currently have it setup (see [here](https://github.com/fjarri/peval/tree/master)). There are commands you can place within the `MANIFEST` file that force the inclusion of the test folder.

Here is an excerpt from: http://stackoverflow.com/questions/32390705/should-i-include-tests-and-pyc-files-when-building-package-with-setuptools

> There are two approaches possible:
> 
> Include tests in the distribution, but not install them. To do this, you put them in a separate folder and include all required files (including the .py ones) explicitly in the MANIFEST.in. As an example, see this excerpt from the manifest of one of my projects:
> 
> ```
> recursive-include test *.py
> include test/pylintrc
> include test/.coveragerc
> ```
> 
> Include tests in the package itself, so that you can run them as import package; package.test() (for instance, numpy does that). No need to tinker with the MANIFEST.in, just put them in the main package directory (as a subpackage or whatever) and treat them as a regular subpackage/module.

Other links I found worth a read:

- http://stackoverflow.com/questions/32390705/should-i-include-tests-and-pyc-files-when-building-package-with-setuptools
- http://python-packaging.readthedocs.io/en/latest/testing.html

A lot of guides recommending using [nose](http://nose.readthedocs.io/en/latest/testing.html):

> **Writing tests is easier**
> 
> nose collects tests from unittest.TestCase subclasses, of course. But you can also write simple test functions, as well as test classes that are not subclasses of unittest.TestCase. nose also supplies a number of helpful functions for writing timed tests, testing for exceptions, and other common use cases. See Writing tests and Testing tools for more.
> 
> **Running tests is easier**
> 
> nose collects tests automatically, as long as you follow some simple guidelines for organizing your library and test code. There’s no need to manually collect test cases into test suites. Running tests is responsive, since nose begins running tests as soon as the first test module is loaded. See Finding and running tests for more.

@ravenmaster001 Our currently structure looks good, we may just need to alter our MANIFEST or import statements to include the tests, docs, etc. We should also look into using nose to make running/writing unit tests easier.
